name: Changelog preview

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Changelog
        id: generate_changelog
        run: |
          yarn lerna version prerelease --preid rc --no-git-tag-version --no-push --yes
          CHANGELOG_PREVIEW=$(bash ./extractVersionChanges.sh)
          if [[ ! -z "${CHANGELOG_PREVIEW}" ]]; then
            echo "::set-output name=exists::true"
            echo "::set-output name=preview::$CHANGELOG_PREVIEW"
          fi
      - uses: marocchino/sticky-pull-request-comment@v2
        if: steps.generate_changelog.outputs.exists == 'true'
        with:
          header: changelog_preview
          message: |
            ```
            ${{ steps.generate_changelog.outputs.preview }}
            ```
      - uses: marocchino/sticky-pull-request-comment@v2
        if: steps.generate_changelog.outputs.exists != 'true'
        with:
          header: changelog_preview
          message: No changelog generated for the current changes on this pull request.
