name: Changelog preview

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]

jobs:
  generate_changelog_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Installation
        run: yarn && yarn lerna exec yarn install
      - name: Generate Changelog
        id: generate_changelog
        run: |
          yarn lerna version prerelease --conventional-commits --conventional-prerelease --preid rc --no-git-tag-version --no-push --yes
          CHANGELOG_PREVIEW=$(bash ./extractVersionChanges.sh)
          if [[ ! -z "${CHANGELOG_PREVIEW}" ]]; then
            echo "::set-output name=exists::true"
            echo "::set-output name=preview::$CHANGELOG_PREVIEW"
          fi
      - uses: marocchino/sticky-pull-request-comment@v2
        if: steps.generate_changelog.outputs.exists == 'true'
        with:
          header: changelog_preview
          message: |
            ```
            ${{ steps.generate_changelog.outputs.preview }}
            ```
      - uses: marocchino/sticky-pull-request-comment@v2
        if: steps.generate_changelog.outputs.exists != 'true'
        with:
          header: changelog_preview
          message: No changelog generated for the current changes on this pull request.
