name: e2e-native-ios

on:
  pull_request:
    branches:
      - develop
      - master
      - 'v[0-9]+.[0-9]+.[0-9]+'
    types: [opened, synchronize]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installation & Build Package
        run: yarn --frozen-lockfile && cd ./examples/NativeMessaging && yarn --frozen-lockfile
      - name: Install Pods
        run: cd ./examples/NativeMessaging && npx pod-install
      - name: Install Detox Dependencies
        run: |
          brew tap wix/brew
          brew install applesimutils
      - name: Build
        run: yarn detox-native-ios:build
      - name: Test
        run: yarn detox-native-ios:test
