name: e2e-native-messaging

on:
  pull_request:
    branches:
      - develop
      - master
    types: [opened, synchronize]

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installation & Build Package
        run: yarn --frozen-lockfile && cd ./examples/NativeMessaging && yarn --frozen-lockfile
      - name: Install Java JDK
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11'
      - name: Prepare Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          avd-name: Pixel4
          script: echo "Finished creating virtual device"
      - name: Build
        run: yarn detox-native-android:build
      - name: Test
        run: yarn detox-native-android:test

  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installation & Build Package
        run: yarn --frozen-lockfile && cd ./examples/NativeMessaging && yarn --frozen-lockfile
      - name: Install Pods
        run: cd ./examples/NativeMessaging && npx pod-install
      - name: Install Detox Dependencies
        run: |
          brew tap wix/brew
          brew install applesimutils
      - name: Build
        run: yarn detox-native-ios:build
      - name: Test
        run: yarn detox-native-ios:test
