name: e2e-native-android

on:
  pull_request:
    branches:
      - develop
      - master
      - 'v[0-9]+.[0-9]+.[0-9]+'
    types: [opened, synchronize]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installation & Build Package
        run: yarn --frozen-lockfile && cd ./examples/NativeMessaging && yarn --frozen-lockfile
      - name: Install Java JDK
        uses: joschi/setup-jdk@v2
        with:
          java-version: '11'
      - name: Generate keystore
        run: cd ./examples/NativeMessaging/android/app && keytool -genkey -noprompt -dname "CN=automation, OU=RN, O=getstream L=NA, S=NA, C=NA" -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000
      - name: Build
        run: yarn detox-native-android:build
      - name: Test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          avd-name: Pixel4
          script: yarn detox-native-android:test
