name: e2e-sample-ios

on:
  pull_request:
    branches:
      - develop
      - master
    types: [opened, synchronize]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node_modules
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: yarn --frozen-lockfile && yarn bootstrap-ci

      - name: Install Pods
        run: cd ./examples/SampleApp && npx pod-install
      - name: Install Detox Dependencies
        run: |
          sudo brew tap wix/brew
          sudo brew install applesimutils
          sudo xcrun simctl list

      - name: Build
        run: yarn detox-sample-ios:build

      - name: Test
        id: detoxRun
        # Sudo is needed to run offline tests
        # -E should only pass secrets if theyre exposed to the job through ENV param
        run: sudo -E yarn detox-sample-ios:test --record-logs failing --record-videos failing

      - uses: actions/upload-artifact@v2
        if: failure() && steps.detoxRun.outcome == 'failure'
        with:
          name: detox-artifacts
          path: ./artifacts
