name: e2e-sample-android

on:
  pull_request:
    branches:
      - develop
      - master
      - v4
    types: [opened, synchronize]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node_modules
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: yarn --frozen-lockfile && yarn bootstrap-ci

      - name: Use specific Java version for sdkmanager to work
        uses: joschi/setup-jdk@v2
        with:
          java-version: 'openjdk8'
          architecture: 'x64'

      - name: Build Android App
        id: buildApp
        run: yarn detox-sample-android:build

      - name: Build Android App retry
        if: failure() && steps.buildApp.outcome == 'failure'
        run: yarn detox-sample-android:build

      - name: Run tests
        id: runTests
        continue-on-error: true
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          cores: 2
          ram-size: 6000
          avd-name: Pixel_29_AOSP
          force-avd-creation: false
          disable-animations: true
          disable-spellchecker: true
          emulator-build: 7425822 # https://github.com/ReactiveCircus/android-emulator-runner/issues/160
          emulator-options: -gpu host -no-audio -no-snapshot -no-window
          script: yarn detox-sample-android:test --record-logs failing --record-videos failing

      - name: Run tests retry
        id: runTests2
        if: failure() && steps.runTests.outcome == 'failure'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          cores: 2
          ram-size: 6000
          avd-name: Pixel_29_AOSP
          force-avd-creation: false
          disable-animations: true
          disable-spellchecker: true
          emulator-build: 7425822 # https://github.com/ReactiveCircus/android-emulator-runner/issues/160
          emulator-options: -gpu host -no-audio -no-snapshot -no-window
          script: yarn detox-sample-android:test --record-logs failing --record-videos failing

      - uses: actions/upload-artifact@v2
        if: failure() && steps.runTests2.outcome == 'failure'
        with:
          name: detox-artifacts
          path: ./artifacts
