name: Next Release

on:
  push:
    branches:
      - lerna

jobs:
  publish-next:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'
      - name: Prepare git
        run: |
          git config --global user.name "Stream Chat RN Next"
          git config --global user.email "next@getstream.io"
      - name: Installation
        run: yarn
      - name: Publish Next release
        run: |
          yarn lerna publish prerelease --no-private --no-push --no-git-tag-version --dist-tag next --preid next.${GITHUB_SHA::7} --no-verify-access --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
